<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="4" failures="0" name="nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest" time="0.111" errors="4" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="C:\java\jdk1.8.0_05\jre\bin"/>
    <property name="java.vm.version" value="25.5-b02"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=";"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.script" value=""/>
    <property name="user.country" value="NL"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="Service Pack 1"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="C:\Users\Remi\Documents\ADMIN\PROJECTEN\icaras"/>
    <property name="java.runtime.version" value="1.8.0_05-b13"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="C:\java\jdk1.8.0_05\jre\lib\endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\Remi\AppData\Local\Temp\"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 7"/>
    <property name="classworlds.conf" value="c:\java\maven\bin\..\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\java\jdk1.8.0_05\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Android\sdk\tools;C:\Android\sdk\platform-tools;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python33\;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby1.9.3\bin;C:\Ruby200\bin;C:\java\jdk1.8.0_05\bin;C:\Program Files (x86)\PC Connectivity Solution\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\TortoiseSVN\bin;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\K-3D 0.8.0.1\bin;C:\Program Files\jEdit;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Git\cmd;C:\java\gradle-2.0\bin;c:\java\maven\bin;c:\java\ant\bin;c:\jruby\bin;C:\Program Files (x86)\Common Files\Hackety Hack\0.r1529\..;.;;."/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="6.1"/>
    <property name="user.home" value="C:\Users\Remi"/>
    <property name="user.timezone" value="Europe/Berlin"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="user.name" value="Remi"/>
    <property name="java.class.path" value="c:\java\maven\bin\..\boot\plexus-classworlds-2.5.1.jar"/>
    <property name="org.slf4j.simpleLogger.defaultLogLevel" value="info"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="C:\java\jdk1.8.0_05\jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher package"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="nl"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_05"/>
    <property name="java.ext.dirs" value="C:\java\jdk1.8.0_05\jre\lib\ext;C:\Windows\Sun\Java\lib\ext"/>
    <property name="sun.boot.class.path" value="C:\java\jdk1.8.0_05\jre\lib\resources.jar;C:\java\jdk1.8.0_05\jre\lib\rt.jar;C:\java\jdk1.8.0_05\jre\lib\sunrsasign.jar;C:\java\jdk1.8.0_05\jre\lib\jsse.jar;C:\java\jdk1.8.0_05\jre\lib\jce.jar;C:\java\jdk1.8.0_05\jre\lib\charsets.jar;C:\java\jdk1.8.0_05\jre\lib\jfr.jar;C:\java\jdk1.8.0_05\jre\classes"/>
    <property name="sun.stderr.encoding" value="cp850"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="c:\java\maven\bin\.."/>
    <property name="file.separator" value="\"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.stdout.encoding" value="cp850"/>
    <property name="sun.desktop" value="windows"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase classname="nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest" name="test_getById" time="0.01">
    <error message="JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement" type="org.springframework.orm.hibernate4.HibernateJdbcException">org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:168)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:343)
	at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:308)
	at org.springframework.orm.hibernate4.HibernateTemplate.flush(HibernateTemplate.java:837)
	at nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest.test_getById(PersoonsRolDaoHibernateTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
	at org.springframework.orm.hibernate4.HibernateTemplate$27.doInHibernate(HibernateTemplate.java:840)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:340)
	... 38 more
Caused by: java.sql.SQLException: Field &apos;gearchiveerd&apos; doesn&apos;t have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 49 more
</error>
    <system-out>15:13:41,716  INFO main transaction.TransactionalTestExecutionListener:276 - Began transaction (1) for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@529c2a9a, testMethod = test_getById@PersoonsRolDaoHibernateTest, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]; transaction manager [org.springframework.orm.hibernate4.HibernateTransactionManager@68b58644]; rollback [true]
Hibernate: select persoonsro0_.rolId as rolId1_24_0_, persoonsro0_.isGearchiveerd as isGearch2_24_0_, persoonsro0_.opmerking as opmerkin3_24_0_, persoonsro0_.functie as functie1_8_0_, persoonsro0_.persoon_relatie_Id as persoon_1_10_0_, persoonsro0_.clazz_ as clazz_0_, persoon1_.relatie_Id as id1_21_1_, persoon1_1_.gearchiveerd as gearchiv2_21_1_, persoon1_1_.opmerking as opmerkin3_21_1_, persoon1_1_.priveRelatie as priveRel4_21_1_, persoon1_.achternaam as achterna1_18_1_, persoon1_.geboortedatum as geboorte2_18_1_, persoon1_.tussenvoegsels as tussenvo3_18_1_, persoon1_.voornaam as voornaam4_18_1_ from ( select rolId, isGearchiveerd, opmerking, functie, null as persoon_relatie_Id, 4 as clazz_ from Contactpersoon union select rolId, isGearchiveerd, opmerking, null as functie, persoon_relatie_Id, 5 as clazz_ from Kandidaat union select rolId, isGearchiveerd, opmerking, null as functie, null as persoon_relatie_Id, 7 as clazz_ from Werknemer ) persoonsro0_ left outer join Persoon persoon1_ on persoonsro0_.persoon_relatie_Id=persoon1_.relatie_Id left outer join Relatie persoon1_1_ on persoon1_.relatie_Id=persoon1_1_.id where persoonsro0_.rolId=?
Hibernate: insert into Kandidaat (isGearchiveerd, opmerking, persoon_relatie_Id, rolId) values (?, ?, ?, ?)
15:13:41,726  WARN main spi.SqlExceptionHelper:144 - SQL Error: 1364, SQLState: HY000
15:13:41,726 ERROR main spi.SqlExceptionHelper:146 - Field &apos;gearchiveerd&apos; doesn&apos;t have a default value
15:13:41,726  INFO main internal.AbstractBatchImpl:208 - HHH000010: On release of batch it still contained JDBC statements
15:13:41,726  INFO main transaction.TransactionalTestExecutionListener:298 - Rolled back transaction after test execution for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@529c2a9a, testMethod = test_getById@PersoonsRolDaoHibernateTest, testException = org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement, mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]
</system-out>
  </testcase>
  <testcase classname="nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest" name="test_delete" time="0.03">
    <error message="JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement" type="org.springframework.orm.hibernate4.HibernateJdbcException">org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:168)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:343)
	at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:308)
	at org.springframework.orm.hibernate4.HibernateTemplate.flush(HibernateTemplate.java:837)
	at nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest.test_delete(PersoonsRolDaoHibernateTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
	at org.springframework.orm.hibernate4.HibernateTemplate$27.doInHibernate(HibernateTemplate.java:840)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:340)
	... 38 more
Caused by: java.sql.SQLException: Field &apos;gearchiveerd&apos; doesn&apos;t have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 49 more
</error>
    <system-out>15:13:41,756  INFO main transaction.TransactionalTestExecutionListener:276 - Began transaction (2) for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@707b1a44, testMethod = test_delete@PersoonsRolDaoHibernateTest, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]; transaction manager [org.springframework.orm.hibernate4.HibernateTransactionManager@68b58644]; rollback [true]
Hibernate: select persoonsro0_.rolId as rolId1_24_0_, persoonsro0_.isGearchiveerd as isGearch2_24_0_, persoonsro0_.opmerking as opmerkin3_24_0_, persoonsro0_.functie as functie1_8_0_, persoonsro0_.persoon_relatie_Id as persoon_1_10_0_, persoonsro0_.clazz_ as clazz_0_, persoon1_.relatie_Id as id1_21_1_, persoon1_1_.gearchiveerd as gearchiv2_21_1_, persoon1_1_.opmerking as opmerkin3_21_1_, persoon1_1_.priveRelatie as priveRel4_21_1_, persoon1_.achternaam as achterna1_18_1_, persoon1_.geboortedatum as geboorte2_18_1_, persoon1_.tussenvoegsels as tussenvo3_18_1_, persoon1_.voornaam as voornaam4_18_1_ from ( select rolId, isGearchiveerd, opmerking, functie, null as persoon_relatie_Id, 4 as clazz_ from Contactpersoon union select rolId, isGearchiveerd, opmerking, null as functie, persoon_relatie_Id, 5 as clazz_ from Kandidaat union select rolId, isGearchiveerd, opmerking, null as functie, null as persoon_relatie_Id, 7 as clazz_ from Werknemer ) persoonsro0_ left outer join Persoon persoon1_ on persoonsro0_.persoon_relatie_Id=persoon1_.relatie_Id left outer join Relatie persoon1_1_ on persoon1_.relatie_Id=persoon1_1_.id where persoonsro0_.rolId=?
Hibernate: insert into Kandidaat (isGearchiveerd, opmerking, persoon_relatie_Id, rolId) values (?, ?, ?, ?)
15:13:41,776  WARN main spi.SqlExceptionHelper:144 - SQL Error: 1364, SQLState: HY000
15:13:41,776 ERROR main spi.SqlExceptionHelper:146 - Field &apos;gearchiveerd&apos; doesn&apos;t have a default value
15:13:41,776  INFO main internal.AbstractBatchImpl:208 - HHH000010: On release of batch it still contained JDBC statements
15:13:41,776  INFO main transaction.TransactionalTestExecutionListener:298 - Rolled back transaction after test execution for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@707b1a44, testMethod = test_delete@PersoonsRolDaoHibernateTest, testException = org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement, mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]
</system-out>
  </testcase>
  <testcase classname="nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest" name="test_getAll" time="0.03">
    <error message="Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd" type="org.springframework.orm.hibernate4.HibernateSystemException">org.springframework.orm.hibernate4.HibernateSystemException: Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:216)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:343)
	at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:308)
	at org.springframework.orm.hibernate4.HibernateTemplate.find(HibernateTemplate.java:864)
	at nl.rsvier.icaras.dao.GenericDaoHibernate.getAll(GenericDaoHibernate.java:62)
	at nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest.test_getAll(PersoonsRolDaoHibernateTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd
	at org.hibernate.property.BasicPropertyAccessor$BasicSetter.set(BasicPropertyAccessor.java:111)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:713)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:362)
	at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:4718)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:188)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1114)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:972)
	at org.hibernate.loader.Loader.doQuery(Loader.java:920)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2553)
	at org.hibernate.loader.Loader.doList(Loader.java:2539)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2369)
	at org.hibernate.loader.Loader.list(Loader.java:2364)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:496)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:231)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1264)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at org.springframework.orm.hibernate4.HibernateTemplate$29.doInHibernate(HibernateTemplate.java:875)
	at org.springframework.orm.hibernate4.HibernateTemplate$29.doInHibernate(HibernateTemplate.java:864)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:340)
	... 39 more
Caused by: java.lang.IllegalArgumentException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.hibernate.property.BasicPropertyAccessor$BasicSetter.set(BasicPropertyAccessor.java:68)
	... 60 more
</error>
    <system-out>15:13:41,796  INFO main transaction.TransactionalTestExecutionListener:276 - Began transaction (3) for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@25673087, testMethod = test_getAll@PersoonsRolDaoHibernateTest, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]; transaction manager [org.springframework.orm.hibernate4.HibernateTransactionManager@68b58644]; rollback [true]
Hibernate: select persoonsro0_.rolId as rolId1_24_, persoonsro0_.isGearchiveerd as isGearch2_24_, persoonsro0_.opmerking as opmerkin3_24_, persoonsro0_.functie as functie1_8_, persoonsro0_.persoon_relatie_Id as persoon_1_10_, persoonsro0_.clazz_ as clazz_ from ( select rolId, isGearchiveerd, opmerking, functie, null as persoon_relatie_Id, 4 as clazz_ from Contactpersoon union select rolId, isGearchiveerd, opmerking, null as functie, persoon_relatie_Id, 5 as clazz_ from Kandidaat union select rolId, isGearchiveerd, opmerking, null as functie, null as persoon_relatie_Id, 7 as clazz_ from Werknemer ) persoonsro0_
Hibernate: select persoon0_.relatie_Id as id1_21_0_, persoon0_1_.gearchiveerd as gearchiv2_21_0_, persoon0_1_.opmerking as opmerkin3_21_0_, persoon0_1_.priveRelatie as priveRel4_21_0_, persoon0_.achternaam as achterna1_18_0_, persoon0_.geboortedatum as geboorte2_18_0_, persoon0_.tussenvoegsels as tussenvo3_18_0_, persoon0_.voornaam as voornaam4_18_0_ from Persoon persoon0_ inner join Relatie persoon0_1_ on persoon0_.relatie_Id=persoon0_1_.id where persoon0_.relatie_Id=?
15:13:41,806  INFO main transaction.TransactionalTestExecutionListener:298 - Rolled back transaction after test execution for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@25673087, testMethod = test_getAll@PersoonsRolDaoHibernateTest, testException = org.springframework.orm.hibernate4.HibernateSystemException: Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of nl.rsvier.icaras.core.relatiebeheer.Rol.gearchiveerd, mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]
</system-out>
  </testcase>
  <testcase classname="nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest" name="test_saveOrUpdate" time="0.041">
    <error message="JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement" type="org.springframework.orm.hibernate4.HibernateJdbcException">org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:168)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:343)
	at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:308)
	at org.springframework.orm.hibernate4.HibernateTemplate.flush(HibernateTemplate.java:837)
	at nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest.test_saveOrUpdate(PersoonsRolDaoHibernateTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:349)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
	at org.springframework.orm.hibernate4.HibernateTemplate$27.doInHibernate(HibernateTemplate.java:840)
	at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:340)
	... 38 more
Caused by: java.sql.SQLException: Field &apos;gearchiveerd&apos; doesn&apos;t have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 49 more
</error>
    <system-out>15:13:41,830  INFO main transaction.TransactionalTestExecutionListener:276 - Began transaction (4) for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@e26af6, testMethod = test_saveOrUpdate@PersoonsRolDaoHibernateTest, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]; transaction manager [org.springframework.orm.hibernate4.HibernateTransactionManager@68b58644]; rollback [true]
Hibernate: select persoonsro0_.rolId as rolId1_24_0_, persoonsro0_.isGearchiveerd as isGearch2_24_0_, persoonsro0_.opmerking as opmerkin3_24_0_, persoonsro0_.functie as functie1_8_0_, persoonsro0_.persoon_relatie_Id as persoon_1_10_0_, persoonsro0_.clazz_ as clazz_0_, persoon1_.relatie_Id as id1_21_1_, persoon1_1_.gearchiveerd as gearchiv2_21_1_, persoon1_1_.opmerking as opmerkin3_21_1_, persoon1_1_.priveRelatie as priveRel4_21_1_, persoon1_.achternaam as achterna1_18_1_, persoon1_.geboortedatum as geboorte2_18_1_, persoon1_.tussenvoegsels as tussenvo3_18_1_, persoon1_.voornaam as voornaam4_18_1_ from ( select rolId, isGearchiveerd, opmerking, functie, null as persoon_relatie_Id, 4 as clazz_ from Contactpersoon union select rolId, isGearchiveerd, opmerking, null as functie, persoon_relatie_Id, 5 as clazz_ from Kandidaat union select rolId, isGearchiveerd, opmerking, null as functie, null as persoon_relatie_Id, 7 as clazz_ from Werknemer ) persoonsro0_ left outer join Persoon persoon1_ on persoonsro0_.persoon_relatie_Id=persoon1_.relatie_Id left outer join Relatie persoon1_1_ on persoon1_.relatie_Id=persoon1_1_.id where persoonsro0_.rolId=?
Hibernate: insert into Kandidaat (isGearchiveerd, opmerking, persoon_relatie_Id, rolId) values (?, ?, ?, ?)
15:13:41,839  WARN main spi.SqlExceptionHelper:144 - SQL Error: 1364, SQLState: HY000
15:13:41,840 ERROR main spi.SqlExceptionHelper:146 - Field &apos;gearchiveerd&apos; doesn&apos;t have a default value
15:13:41,840  INFO main internal.AbstractBatchImpl:208 - HHH000010: On release of batch it still contained JDBC statements
15:13:41,844  INFO main transaction.TransactionalTestExecutionListener:298 - Rolled back transaction after test execution for test context [DefaultTestContext@4f5b08d testClass = PersoonsRolDaoHibernateTest, testInstance = nl.rsvier.icaras.dao.relatiebeheer.PersoonsRolDaoHibernateTest@e26af6, testMethod = test_saveOrUpdate@PersoonsRolDaoHibernateTest, testException = org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1364]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement, mergedContextConfiguration = [MergedContextConfiguration@3c87fdf2 testClass = PersoonsRolDaoHibernateTest, locations = &apos;{classpath:icarastestdb-context.xml}&apos;, classes = &apos;{}&apos;, contextInitializerClasses = &apos;[]&apos;, activeProfiles = &apos;{}&apos;, contextLoader = &apos;org.springframework.test.context.support.DelegatingSmartContextLoader&apos;, parent = [null]]]
</system-out>
  </testcase>
</testsuite>